version: "3.9"

services:
  backend:
    build:
      context: ./backend # use only the backend folder as build context
      dockerfile: Dockerfile # Dockerfile inside backend folder
    container_name: kira-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # hot reload in dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend # use only the frontend folder as build context
      dockerfile: Dockerfile # Dockerfile inside frontend folder
    container_name: kira-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      HOSTNAME: "0.0.0.0"
      PORT: "3000"
      WATCHPACK_POLLING: "true" # key for hot reload in Docker
      CHOKIDAR_USEPOLLING: "true" # extra help on some OSes
    volumes:
      - ./frontend:/app # hot reload in dev
      - /app/node_modules # keep node_modules inside container
