/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as shopLayoutRouteImport } from './routes/(shop)/_layout'
import { Route as AuthSignUpSplatRouteImport } from './routes/auth/sign-up.$'
import { Route as AuthSignInSplatRouteImport } from './routes/auth/sign-in.$'
import { Route as shopLayoutDashboardIdRouteImport } from './routes/(shop)/_layout.dashboard.$id'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const shopLayoutRoute = shopLayoutRouteImport.update({
  id: '/(shop)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/auth/sign-up/$',
  path: '/auth/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/auth/sign-in/$',
  path: '/auth/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const shopLayoutDashboardIdRoute = shopLayoutDashboardIdRouteImport.update({
  id: '/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => shopLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$id': typeof shopLayoutDashboardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/dashboard/$id': typeof shopLayoutDashboardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(shop)/_layout': typeof shopLayoutRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/auth/sign-in/$': typeof AuthSignInSplatRoute
  '/auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/(shop)/_layout/dashboard/$id': typeof shopLayoutDashboardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth/sign-in/$' | '/auth/sign-up/$' | '/dashboard/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/sign-in/$' | '/auth/sign-up/$' | '/dashboard/$id'
  id:
    | '__root__'
    | '/(public)'
    | '/(shop)/_layout'
    | '/(public)/'
    | '/auth/sign-in/$'
    | '/auth/sign-up/$'
    | '/(shop)/_layout/dashboard/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  shopLayoutRoute: typeof shopLayoutRouteWithChildren
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(shop)/_layout': {
      id: '/(shop)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof shopLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up/$': {
      id: '/auth/sign-up/$'
      path: '/auth/sign-up/$'
      fullPath: '/auth/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/$': {
      id: '/auth/sign-in/$'
      path: '/auth/sign-in/$'
      fullPath: '/auth/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/_layout/dashboard/$id': {
      id: '/(shop)/_layout/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof shopLayoutDashboardIdRouteImport
      parentRoute: typeof shopLayoutRoute
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface shopLayoutRouteChildren {
  shopLayoutDashboardIdRoute: typeof shopLayoutDashboardIdRoute
}

const shopLayoutRouteChildren: shopLayoutRouteChildren = {
  shopLayoutDashboardIdRoute: shopLayoutDashboardIdRoute,
}

const shopLayoutRouteWithChildren = shopLayoutRoute._addFileChildren(
  shopLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  shopLayoutRoute: shopLayoutRouteWithChildren,
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
