/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as storeStoreIdRouteImport } from './routes/(store)/store.$id'
import { Route as storeDashboardIdRouteImport } from './routes/(store)/dashboard.$id'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const storeStoreIdRoute = storeStoreIdRouteImport.update({
  id: '/(store)/store/$id',
  path: '/store/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const storeDashboardIdRoute = storeDashboardIdRouteImport.update({
  id: '/(store)/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof publicIndexRoute
  '/dashboard/$id': typeof storeDashboardIdRoute
  '/store/$id': typeof storeStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof publicIndexRoute
  '/dashboard/$id': typeof storeDashboardIdRoute
  '/store/$id': typeof storeStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(public)/': typeof publicIndexRoute
  '/(store)/dashboard/$id': typeof storeDashboardIdRoute
  '/(store)/store/$id': typeof storeStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard/$id' | '/store/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard/$id' | '/store/$id'
  id:
    | '__root__'
    | '/(public)'
    | '/(public)/'
    | '/(store)/dashboard/$id'
    | '/(store)/store/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  storeDashboardIdRoute: typeof storeDashboardIdRoute
  storeStoreIdRoute: typeof storeStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(store)/store/$id': {
      id: '/(store)/store/$id'
      path: '/store/$id'
      fullPath: '/store/$id'
      preLoaderRoute: typeof storeStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(store)/dashboard/$id': {
      id: '/(store)/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof storeDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  storeDashboardIdRoute: storeDashboardIdRoute,
  storeStoreIdRoute: storeStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
