/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as shopShopIdRouteImport } from './routes/(shop)/$shopId'
import { Route as shopDashboardIdRouteImport } from './routes/(shop)/dashboard.$id'

const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const shopShopIdRoute = shopShopIdRouteImport.update({
  id: '/(shop)/$shopId',
  path: '/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const shopDashboardIdRoute = shopDashboardIdRouteImport.update({
  id: '/(shop)/dashboard/$id',
  path: '/dashboard/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$shopId': typeof shopShopIdRoute
  '/': typeof publicIndexRoute
  '/dashboard/$id': typeof shopDashboardIdRoute
}
export interface FileRoutesByTo {
  '/$shopId': typeof shopShopIdRoute
  '/': typeof publicIndexRoute
  '/dashboard/$id': typeof shopDashboardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(public)': typeof publicRouteRouteWithChildren
  '/(shop)/$shopId': typeof shopShopIdRoute
  '/(public)/': typeof publicIndexRoute
  '/(shop)/dashboard/$id': typeof shopDashboardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$shopId' | '/' | '/dashboard/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/$shopId' | '/' | '/dashboard/$id'
  id:
    | '__root__'
    | '/(public)'
    | '/(shop)/$shopId'
    | '/(public)/'
    | '/(shop)/dashboard/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  publicRouteRoute: typeof publicRouteRouteWithChildren
  shopShopIdRoute: typeof shopShopIdRoute
  shopDashboardIdRoute: typeof shopDashboardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(shop)/$shopId': {
      id: '/(shop)/$shopId'
      path: '/$shopId'
      fullPath: '/$shopId'
      preLoaderRoute: typeof shopShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(shop)/dashboard/$id': {
      id: '/(shop)/dashboard/$id'
      path: '/dashboard/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof shopDashboardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface publicRouteRouteChildren {
  publicIndexRoute: typeof publicIndexRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicIndexRoute: publicIndexRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  publicRouteRoute: publicRouteRouteWithChildren,
  shopShopIdRoute: shopShopIdRoute,
  shopDashboardIdRoute: shopDashboardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
