FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Keep container alive + hot reload
CMD ["npx", "nodemon", "--legacy-watch", "--watch", "src", "--ext", "ts,js,json", "--exec", "node", "--loader", "ts-node/esm", "src/index.ts"]

EXPOSE 2109